#!/bin/bash
set -e

if [[ "$(whoami)" != "root" ]] && ! [ "$(groups | grep -F 'docker')" ]; then
  >&2 echo "User must be either root or in group docker"
  exit 1
fi

container_name="$1"
if ! [[ "$container_name" ]]; then
  >&2 echo "Requires container name as first argument"
  exit 1
fi

available_containers="$(docker container ls -a --format='table {{.Names}}' | tail -n +2)"
if ! echo "$available_containers" | grep -qxF "$container_name"; then
  >&2 echo "'$container_name' is not an available container"
  exit 1
fi

running_containers="$(docker container ls --format='table {{.Names}}' | tail -n +2)"
if ! echo "$running_containers" | grep -qxF "$container_name"; then
  docker start "$container_name" > /dev/null
fi

shift
if [[ "$#" == 0 ]]; then
  exec docker exec -it "$container_name" /bin/bash -i
else
  exec docker exec -i "$container_name" "$@"
fi
